image: python:3.11

stages:
  - test

variables:
  PYTHONDONTWRITEBYTECODE: "1"
  PYTHONUNBUFFERED: "1"

before_script:
  - python -V
  - pip install uv

ruff:
  stage: test
  script:
    - uv sync
    - ruff check .

test:
  stage: test
  script:
    - uv sync
    - pytest # Run pytest for testing
